from .bull import Bull
from .donkey import Donkey
from .duck import Duck
from .fish import Fish
from .frog import Frog
from .goat import Goat
from .lizard import Lizard
from .llama import Llama
from .parakeet import Parakeet
from .pigeon import Pigeon
from .rabbit import Rabbit
from .rhino import Rhino
from .snail import Snail
from .snake import Snake
from .stork import Stork